### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Alpha-1729** [maaami98/Evil-Twin-For-ESP8266#3]
tplink.icons.png is not uploading. and causing error.

```
    return callback(*args, **kwargs)
  File "c:\users\lazy-coder\appdata\local\programs\python\python36\lib\site-packages\ampy\cli.py", line 263, in put
    board_files.put(remote, infile.read())
  File "c:\users\lazy-coder\appdata\local\programs\python\python36\lib\site-packages\ampy\files.py", line 208, in put
    self._pyboard.enter_raw_repl()
  File "c:\users\lazy-coder\appdata\local\programs\python\python36\lib\site-packages\ampy\pyboard.py", line 192, in enter_raw_repl
    raise PyboardError('could not enter raw repl')
ampy.pyboard.PyboardError: could not enter raw repl
```

also 
```
HTTP Server listening on ('0.0.0.0', 80)
DNS Server listening on ('0.0.0.0', 53)
Traceback (most recent call last):
  File "main.py", line 130, in <module>
  File "main.py", line 61, in start
  File "main.py", line 85, in handle_http
  File "captive_http.py", line 44, in handle
  File "captive_http.py", line 152, in read
  File "captive_http.py", line 74, in parse_request
  File "captive_http.py", line 73, in <dictcomp>
ValueError: need more than 1 values to unpack

```

Can you tell what to do after connected to captive portal.

**Comment by maaami98** [comment]
The icon is too big, maybe it is breaking the stabilization caused by it.  I'll test it and update the code.  You can try by deleting the tplink.icons.png file from the device.

**Comment by Alpha-1729** [comment]
Nice work.

Also I am not gettting any login page.

**Comment by maaami98** [comment]
Code updated :)

**Comment by Alpha-1729** [comment]
Bro 3.upload_files.bat that file is not working

**Comment by maaami98** [comment]
what is the error output

**Comment by Alpha-1729** [comment]
No error .. stuck at batch script

**Comment by Alpha-1729** [comment]
> 
> 
> No error .. stuck at batch script

![Screenshot_2](https://user-images.githubusercontent.com/44919646/100779718-c862f300-342e-11eb-95bc-4685842f467b.png)

**Comment by Alpha-1729** [comment]
no files uploading ....

**Comment by maaami98** [comment]
Does the python window come up when connecting through the serial port?

**Comment by Alpha-1729** [comment]
No

**Comment by maaami98** [comment]
You can flash esp8266 again or you can use the release version

**Comment by Alpha-1729** [comment]
I flashed the image.. no wifi hotspot created.

**Comment by maaami98** [comment]
Did you flash with esptool or with esp8266flasher?

**Comment by Alpha-1729** [comment]
esp8266 flasher

**Comment by maaami98** [comment]
what is the esp model you use, 01, 12F 12E etc.

**Comment by Alpha-1729** [comment]
Nodemcu
12E

**Comment by Alpha-1729** [comment]
nodemcu 12E

**Comment by maaami98** [comment]
I use nodemcu v3 too but it works

**Comment by maaami98** [comment]
https://micropython.org/download/esp8266/

can you try to install

**Comment by Alpha-1729** [comment]
Still not working..
could you please explain the steps you followed.

**Comment by Alpha-1729** [comment]
I am also using the v3.

**Comment by AlexTryHarder** [comment]
> https://micropython.org/download/esp8266/
> 
> can you try to install

I managed to fix the issue by flashing my esp with NodeMcu ESP8266Flasher tool
